services:
  - type: web
    name: music-library-drn-march22
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci
    startCommand: npm run migrate && node index.js
    envVars:
      - key: PGDATABASE
        fromDatabase: 
          name: music-library-database-drn-march23
          property: database
      - key: PGUSER
        fromDatabase: 
          name: music-library-database-drn-march23
          property: user
      - key: PGPASSWORD
        fromDatabase: 
          name: music-library-database-drn-march23
          property: password
      - key: PGHOST
        fromDatabase: 
          name: music-library-database-drn-march23
          property: host
      - key: PGPORT
        fromDatabase: 
          name: music-library-database-drn-march23
          property: port

databases:
  - name: music-library-database-drn-march23
    plan: free
    region: frankfurt
    databaseName: music_library
    ipAllowList: []
